/* SPDX-License-Identifier: Apache-2.0 */
#pragma once

/* Defaults are also exposed through Kconfig. Host builds may override them. */
#ifndef CAGENT_ADDONS_MAX_NODES
#define CAGENT_ADDONS_MAX_NODES 4
#endif

#ifndef CAGENT_ADDONS_MAX_NODE_COMMANDS
#define CAGENT_ADDONS_MAX_NODE_COMMANDS 8
#endif

#ifndef CAGENT_ADDONS_MAX_NODE_TOOLS
#define CAGENT_ADDONS_MAX_NODE_TOOLS 8
#endif

#ifndef CAGENT_ADDONS_MAX_MCP_TOOLS
#define CAGENT_ADDONS_MAX_MCP_TOOLS 4
#endif

#ifndef CAGENT_ADDONS_MAX_REMOTE_TOOLS
#define CAGENT_ADDONS_MAX_REMOTE_TOOLS 12
#endif

#ifndef CAGENT_ADDONS_MAX_PENDING
#define CAGENT_ADDONS_MAX_PENDING 4
#endif

#ifndef CAGENT_ADDONS_INVOKE_TIMEOUT_MS
#define CAGENT_ADDONS_INVOKE_TIMEOUT_MS 10000
#endif

#ifndef CAGENT_ADDONS_GATEWAY_STACK_SIZE
#define CAGENT_ADDONS_GATEWAY_STACK_SIZE 8192
#endif

#ifndef CAGENT_ADDONS_TRANSPORT_STACK_SIZE
#define CAGENT_ADDONS_TRANSPORT_STACK_SIZE 8192
#endif

#ifndef CAGENT_ADDONS_NODE_CLIENT_STACK_SIZE
#define CAGENT_ADDONS_NODE_CLIENT_STACK_SIZE 8192
#endif

#ifndef CAGENT_ADDONS_NODE_QUEUE_SIZE
#define CAGENT_ADDONS_NODE_QUEUE_SIZE 4
#endif

#ifndef CAGENT_ADDONS_WS_CONNECT_TIMEOUT_MS
#define CAGENT_ADDONS_WS_CONNECT_TIMEOUT_MS 5000
#endif

#ifndef CAGENT_ADDONS_WS_IO_TIMEOUT_MS
#define CAGENT_ADDONS_WS_IO_TIMEOUT_MS 2000
#endif

#ifndef CAGENT_ADDONS_RECV_BUF_SIZE
#define CAGENT_ADDONS_RECV_BUF_SIZE 4096
#endif

#ifndef CAGENT_ADDONS_MAX_RESULT_SIZE
#define CAGENT_ADDONS_MAX_RESULT_SIZE 4096
#endif

#ifndef CAGENT_ADDONS_MAX_SCHEMA_SIZE
#define CAGENT_ADDONS_MAX_SCHEMA_SIZE 1024
#endif

#ifndef CAGENT_ADDONS_MAX_DESCRIPTION_SIZE
#define CAGENT_ADDONS_MAX_DESCRIPTION_SIZE 256
#endif

#ifndef CAGENT_ADDONS_MAX_PUBLIC_NAME_SIZE
#define CAGENT_ADDONS_MAX_PUBLIC_NAME_SIZE 64
#endif

#ifndef CAGENT_ADDONS_MCP_RESPONSE_BUF_SIZE
#define CAGENT_ADDONS_MCP_RESPONSE_BUF_SIZE 4096
#endif

#define CAGENT_ADDONS_NODE_PROTOCOL_VERSION 3
#define CAGENT_ADDONS_NODE_DEFAULT_PORT 18790
#define CAGENT_ADDONS_NODE_DEFAULT_PATH "/"
#define CAGENT_ADDONS_MCP_DEFAULT_PORT 18800
#define CAGENT_ADDONS_MCP_QEMU_DEFAULT_HOST "10.0.2.2"
#define CAGENT_ADDONS_DEFAULT_CONFIG_PATH "/data/cagent_addons.json"

#define CAGENT_ADDONS_NODE_ID_SIZE 32
#define CAGENT_ADDONS_COMMAND_NAME_SIZE 64
#define CAGENT_ADDONS_AUTH_TOKEN_MAX_LENGTH 255
#define CAGENT_ADDONS_FRAME_ID_SIZE 48
#define CAGENT_ADDONS_FRAME_NAME_SIZE 64
#define CAGENT_ADDONS_ERROR_CODE_SIZE 32
#define CAGENT_ADDONS_ERROR_MESSAGE_SIZE 256
#define CAGENT_ADDONS_ROUTE_ID_SIZE 96

/* Includes the largest RFC 6455 header; payload capacity remains RECV_BUF_SIZE. */
#define CAGENT_ADDONS_WS_STORAGE_SIZE (CAGENT_ADDONS_RECV_BUF_SIZE + 14)
