############################################################################
# Contest 2026 team 031 SC2336 V4L2 video capture test
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = video_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_031_VIDEO_TEST)

MAINSRC = video_test_main.c

include $(APPDIR)/Application.mk
