############################################################################
# Contest 2026 team 031 MIPI-DSI Host probe
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = dsi_probe
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_031_DSI_PROBE)

MAINSRC = dsi_probe_main.c

include $(APPDIR)/Application.mk
