#!/usr/bin/env python3
"""Generate the SmartHome LVGL A8 icon library from prototype-web PNGs.

The PNG files are the source of truth.  This script crops transparent margins,
fits the glyph into a standard canvas and writes uncompressed LVGL v9 A8 image
descriptors.  Generated C files are intentionally committed: firmware builds
must not depend on Pillow or the QuickApp tooling.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "quickapp/smart_home_ui/prototype-web/assets/icons"
ICON_DIR = ROOT / "demos/smart_home/src/ui/lvgl/icons"
OUTPUT_DIR = ICON_DIR / "generated"
HEADER = ICON_DIR / "smart_home_lvgl_png_icons.h"
LOOKUP_SOURCE = ICON_DIR / "smart_home_lvgl_png_icons.c"

BASE_SIZE = 32
SMALL_SIZE = 20
LARGE_SIZE = 48

# Top/status/navigation and compact device glyphs need a native 20 px source.
SMALL_ICONS = {
    "air-conditioning", "bulb", "camera", "cloud-rain", "devices", "dots",
    "home", "microphone", "moon", "propeller", "robot", "shield",
    "sparkle-2", "sun", "temperature", "wifi",
}

# These are the only glyphs used as visual anchors on the 1024x600 home page.
LARGE_ICONS = {
    "air-conditioning", "camera", "cloud-rain", "home", "home-shield",
    "music-circle-outline", "robot", "sparkle-2",
}


def symbol_name(stem: str, size: int) -> str:
    return "smart_home_icon_{}_{}".format(stem.replace("-", "_"), size)


def icon_sizes(stem: str) -> list[int]:
    sizes = [BASE_SIZE]
    if stem in SMALL_ICONS:
        sizes.insert(0, SMALL_SIZE)
    if stem in LARGE_ICONS:
        sizes.append(LARGE_SIZE)
    return sizes


def alpha_canvas(source: Path, size: int) -> Image.Image:
    """Return a consistently padded A8 icon canvas of *size* square pixels."""
    image = Image.open(source).convert("RGBA")
    alpha = image.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise ValueError(f"icon has no visible pixels: {source}")

    cropped = alpha.crop(bbox)
    # Keep the visible ink within an 80% square.  This removes inconsistent
    # PNG whitespace while retaining enough breathing room for antialiasing.
    inner = max(1, int(round(size * 0.80)))
    scale = min(inner / cropped.width, inner / cropped.height)
    width = max(1, int(round(cropped.width * scale)))
    height = max(1, int(round(cropped.height * scale)))
    resampling = getattr(getattr(Image, "Resampling", Image), "LANCZOS")
    resized = cropped.resize((width, height), resampling)
    canvas = Image.new("L", (size, size), 0)
    canvas.paste(resized, ((size - width) // 2, (size - height) // 2))
    return canvas


def alpha_data(alpha: Image.Image) -> bytes:
    """Return full alpha bytes for the LVGL software renderer's A8 format."""
    return alpha.tobytes()


def byte_rows(data: bytes, width: int = 12) -> Iterable[str]:
    for offset in range(0, len(data), width):
        yield "    " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + width]) + ","


def write_icon(source: Path, size: int) -> None:
    stem = source.stem
    symbol = symbol_name(stem, size)
    data = alpha_data(alpha_canvas(source, size))
    output = OUTPUT_DIR / f"{stem}_{size}.c"
    lines = [
        "/* Generated by scripts/generate_smart_home_lvgl_icons.py; do not edit. */",
        "#include <lvgl/lvgl.h>",
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {symbol}_map[] = {{",
        *byte_rows(data),
        "};",
        "",
        f"const lv_image_dsc_t {symbol} = {{",
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
        "    .header.cf = LV_COLOR_FORMAT_A8,",
        "    .header.flags = 0,",
        f"    .header.w = {size},",
        f"    .header.h = {size},",
        f"    .header.stride = {size},",
        f"    .data_size = sizeof({symbol}_map),",
        f"    .data = {symbol}_map,",
        "};",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def write_header(sources: list[Path]) -> None:
    lines = [
        "/** Generated SmartHome PNG-derived LVGL A8 icon declarations. */",
        "#pragma once",
        "",
        "#include <lvgl/lvgl.h>",
        "",
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif",
        "",
    ]
    for source in sources:
        for size in icon_sizes(source.stem):
            lines.append(f"extern const lv_image_dsc_t {symbol_name(source.stem, size)};")
    lines += [
        "",
        "/* `name` must use the stable `asset:<png-stem>` vocabulary. */",
        "const lv_image_dsc_t *smart_home_lvgl_png_icon_get(const char *name, int requested_size);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    HEADER.write_text("\n".join(lines), encoding="utf-8")


def write_lookup(sources: list[Path]) -> None:
    lines = [
        "/* Generated by scripts/generate_smart_home_lvgl_icons.py; do not edit. */",
        "#include \"smart_home_lvgl_png_icons.h\"",
        "",
        "#include <string.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    const lv_image_dsc_t *small;",
        "    const lv_image_dsc_t *base;",
        "    const lv_image_dsc_t *large;",
        "} smart_home_png_icon_entry_t;",
        "",
        "static const smart_home_png_icon_entry_t g_png_icons[] = {",
    ]
    for source in sources:
        stem = source.stem
        small = f"&{symbol_name(stem, SMALL_SIZE)}" if stem in SMALL_ICONS else "NULL"
        large = f"&{symbol_name(stem, LARGE_SIZE)}" if stem in LARGE_ICONS else "NULL"
        lines.append(
            f'    {{"asset:{stem}", {small}, &{symbol_name(stem, BASE_SIZE)}, {large}}},'
        )
    lines += [
        "};",
        "",
        "const lv_image_dsc_t *smart_home_lvgl_png_icon_get(const char *name, int requested_size)",
        "{",
        "    size_t i;",
        "",
        "    if (!name) {",
        "        return NULL;",
        "    }",
        "    for (i = 0; i < sizeof(g_png_icons) / sizeof(g_png_icons[0]); i++) {",
        "        const smart_home_png_icon_entry_t *entry = &g_png_icons[i];",
        "",
        "        if (strcmp(name, entry->name) != 0) {",
        "            continue;",
        "        }",
        "        if (requested_size <= 24 && entry->small) {",
        "            return entry->small;",
        "        }",
        "        if (requested_size > 32 && entry->large) {",
        "            return entry->large;",
        "        }",
        "        return entry->base;",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]
    LOOKUP_SOURCE.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    if not SOURCE_DIR.is_dir():
        raise SystemExit(f"missing source directory: {SOURCE_DIR}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    sources = sorted(SOURCE_DIR.glob("*.png"))
    if not sources:
        raise SystemExit(f"no PNG icons under: {SOURCE_DIR}")

    expected = set()
    for source in sources:
        for size in icon_sizes(source.stem):
            output = OUTPUT_DIR / f"{source.stem}_{size}.c"
            expected.add(output)
            write_icon(source, size)
    for stale in OUTPUT_DIR.glob("*.c"):
        if stale not in expected:
            stale.unlink()
    write_header(sources)
    write_lookup(sources)
    print(f"generated {len(expected)} LVGL A8 images from {len(sources)} PNG sources")


if __name__ == "__main__":
    main()
